#!/bin/sh

FILES=$(git diff --diff-filter=d --name-only HEAD | { grep '.php$' || true; })
for file in $FILES; do
  ./vendor/bin/phpcs --extensions=php --standard=phpcs.xml "$file"
  ./vendor/bin/phpmd "$file" text phpmd.xml --exclude vendor
done
# XDEBUG_MODE=coverage ./vendor/bin/phpunit --coverage-text --coverage-filter=app/ tests/
