name: Laravel 8
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    container:
      image: php:8.0-cli
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare
        run: |
          apt update
          apt install -y libzip-dev unzip
          pecl install xdebug
          docker-php-ext-enable xdebug
          cp /usr/local/etc/php/php.ini-development /usr/local/etc/php/php.ini
          echo 'xdebug.mode=coverage' >> /usr/local/etc/php/php.ini
          curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
      - name: PHPUnit
        run: |
          composer require orchestra/testbench:^v6 --dev
          ./vendor/bin/phpunit --coverage-clover coverage.xml --coverage-filter src/ tests/
      - name: Lint
        run: |
          ./vendor/bin/phpcs --standard=PSR12 src/ tests/
          ./vendor/bin/phpmd . text src/stubs/phpmd.xml
      - name: codecov
        uses: codecov/codecov-action@v2
        with:
          name: laravel-8
