name: Laravel 11
on:
  push:
    paths-ignore:
      - "**.md"
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container:
      image: laravelfans/laravel:11-dev
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: PHPUnit
        env:
          XDEBUG_MODE: coverage
        run: |
          composer require orchestra/testbench:^v9 --dev
          ./vendor/bin/phpunit --coverage-clover coverage.xml --coverage-filter src/ tests/
      -
        name: Lint
        run: |
          ./vendor/bin/phpcs --standard=PSR12 src/ tests/
          ./vendor/bin/phpmd . text src/stubs/phpmd.xml
          ./vendor/bin/pint --test --config src/stubs/pint.json
      -
        name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          name: laravel-11
          token: ${{ secrets.CODECOV_TOKEN }}
      -
        name: install in real Laravel project
        run: |
          rm -rf laravel-demo
          composer create-project --prefer-dist laravel/laravel laravel-demo "11.*"
          cd laravel-demo && composer require --dev laravel-fans/lint:dev-${{ github.ref_name }} && php artisan lint:publish
          php artisan lint:code --help
